# Local development values would go here
logging:
  config: src/test/resources/logback-test.xml
  level:
    web: INFO
    no.obos: DEBUG

services:
  spring-boot-admin:
    #No URL disables SBA
    url:

localDirPathToAs400: ./tmp/toAs400
localDirPathFromAs400: ./tmp/fromAs400

file-server:
    username: ${AS400_USERNAME}
    password: ${AS400_PASSWORD}
    host: obos.obos.no
    remoteBaseDir: hi
    localDirPathToAs400: ${localDirPathToAs400}
    localDirPathFromAs400: ${localDirPathFromAs400}

localdirpath:
  toAs400: ${localDirPathToAs400}
  fromAs400: ${localDirPathFromAs400}
