# Test environment specific properties goes here
obos:
  baseUrl:
    api: http://test-api.obos.no
    app: http://test-app.obos.no
    token-service: http://testsso.obos.no

localDirPathToAs400: /opt/app/tmp/toAs400
localDirPathFromAs400: /opt/app/tmp/fromAs400

file-server:
    username: ${AS400_USERNAME}
    password: ${AS400_PASSWORD}
    host: obos.obos.no
    remoteBaseDir: hi
    localDirPathToAs400: ${localDirPathToAs400}
    localDirPathFromAs400: ${localDirPathFromAs400}

localDirpath:
  toAs400: ${localDirPathToAs400}
  fromAs400: ${localDirPathFromAs400}

logging:
  config: /opt/app/logback-spring.xml
  level:
    no.obos: INFO
    org.springframework: WARN
    org.hibernate: WARN