# Local development values would go here
logging:
  config: src/test/resources/logback-test.xml
  level:
    web: INFO
    no.obos: DEBUG

services:
  spring-boot-admin:
    #No URL disables SBA
    url:
