# Test environment specific properties goes here
obos:
  baseUrl:
    api: http://test-api.obos.no
    app: http://test-app.obos.no
    token-service: http://testsso.obos.no

logging:
  config: /opt/app/logback-spring.xml
  level:
    no.obos: INFO
    org.springframework: WARN
    org.hibernate: WARN

localDirPathTo: /opt/app/tmp/to
localDirPathFrom: /opt/app/tmp/from

file-server:
    username: ${AS400_USERNAME}
    password: ${AS400_PASSWORD}
    host: obos.obos.no
    remoteBaseDir: hi
    localDirPathTo: ${localDirPathTo}

localdirpath:
  toPath: ${localDirPathTo}
  fromPath: ${localDirPathFrom}