# Insert properties with mock values that are necessary for the service context tests to run
spring:
  application:
    name: hi-filetransfers

localDirPathToAs400: ./resources/tmp/to
localDirPathFromAs400: ./resources/tmp/from

file-server:
  username: mock
  password: mock
  host: mock
  remoteBaseDir: hi
  localDirPathToAs400: ${localDirPathToAs400}
  localDirPathFromAs400: ${localDirPathToAs400}

localdirpath:
  toAs400: ${localDirPathToAs400}
  fromAs400: ${localDirPathFromAs400}