# Insert properties with mock values that are necessary for the service context tests to run
spring:
  application:
    name: hi-filetransfers

file-server:
  username: mock
  password: mock
  host: mock
  remoteBaseDir: hi
  localDirPathTo: ./resources/test/to
  localDirPathFrom: ./resources/test/from

localdirpath:
  toPath: ./resources/test/to
  fromPath: ./resources/test/from